import React, { useState, useEffect } from 'react';
import { Copy, Check, Upload, Download, FileText, ChevronDown, Key } from 'lucide-react';
import { ApiKey } from '../types';

interface LuaIntegrationProps {
  keys: ApiKey[];
}

export const LuaIntegration: React.FC<LuaIntegrationProps> = ({ keys }) => {
  const [copied, setCopied] = useState(false);
  const [keyCopied, setKeyCopied] = useState(false);
  const [selectedKey, setSelectedKey] = useState<string>('');
  const [payloadScript, setPayloadScript] = useState<string>('-- loadstring(game:HttpGet("https://raw.githubusercontent.com/..."))()');
  const [fileName, setFileName] = useState<string>('');

  useEffect(() => {
    if (keys.length > 0 && !selectedKey) {
      setSelectedKey(keys[0].key);
    }
  }, [keys, selectedKey]);

  const generateFullScript = () => {
    return `getgenv().Key = "${selectedKey || 'PUT_YOUR_KEY_HERE'}"

-- Script Autogenerated by LuaAuth
local StarterGui = game:GetService("StarterGui")

-- Function to check key
local function verifyKey()
    local url = "https://exviun.github.io/verify?key=" .. getgenv().Key
    local TIMEKEY = game:HttpGet("https://exviun.github.io/Time?Key=" .. getgenv().Key)
    
    -- In a real environment, you would use:
    -- local response = game:HttpGet(url)
    -- local data = game:GetService("HttpService"):JSONDecode(response)
    
    -- MOCKING RESPONSE LOGIC FOR DEMONSTRATION
    -- Replace "Status" with the actual JSON field your API returns
    local status = "Success" -- Options: "Success", "Expired", "Invalid"
    
    if status == "Success" then
        StarterGui:SetCore("SendNotification", {
            Title = "Exviun API";
            Text = "Key Valid. Expires in: " .. TIMEKEY;
            Duration = 5;
        })
        
        print("Key Validated! Loading Payload...")
        
        -- --- START OF PAYLOAD ---
        ${payloadScript}
        -- --- END OF PAYLOAD ---
        
    elseif status == "Expired" then
        game.Players.LocalPlayer:Kick("Key Expried, plz buy a new key")
    else
        game.Players.LocalPlayer:Kick("Invalid Key")
    end
end

verifyKey()
`.trim();
  };

  const handleCopyScript = () => {
    navigator.clipboard.writeText(generateFullScript());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyKey = () => {
    if (selectedKey) {
      navigator.clipboard.writeText(selectedKey);
      setKeyCopied(true);
      setTimeout(() => setKeyCopied(false), 2000);
    }
  };

  const handleDownloadScript = () => {
    const content = generateFullScript();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `loader_${fileName || 'script'}.lua`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = (event) => {
      if (typeof event.target?.result === 'string') {
        setPayloadScript(event.target.result);
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="bg-black/60 backdrop-blur-md border border-hacker-border/50 rounded-xl p-4 md:p-6 shadow-xl">
        <h2 className="text-xl md:text-2xl font-bold text-white mb-4">Lua Loader Configuration</h2>
        
        {/* Settings Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          
          {/* Key Selection */}
          <div>
            <label className="block text-sm font-mono text-gray-400 mb-2">Select Active Key</label>
            <div className="flex gap-2">
              <div className="relative flex-1">
                <select
                  value={selectedKey}
                  onChange={(e) => setSelectedKey(e.target.value)}
                  className="w-full appearance-none bg-black/50 border border-hacker-border/50 text-hacker-green p-3 pr-10 rounded focus:border-hacker-green focus:outline-none cursor-pointer font-mono text-sm backdrop-blur-sm"
                >
                  <option value="">-- Select a Key --</option>
                  {keys.map((k) => (
                    <option key={k.id} value={k.key}>
                      {k.key} ({k.note})
                    </option>
                  ))}
                </select>
                <ChevronDown className="absolute right-3 top-3 text-gray-500 pointer-events-none" size={16} />
              </div>
              <button
                onClick={handleCopyKey}
                disabled={!selectedKey}
                className="bg-slate-800/80 border border-slate-600/50 hover:bg-slate-700 text-white p-3 rounded transition-colors disabled:opacity-50 backdrop-blur-sm"
                title="Copy Key Only"
              >
                {keyCopied ? <Check size={18} className="text-green-400" /> : <Key size={18} />}
              </button>
            </div>
          </div>

          {/* File Upload */}
          <div>
             <label className="block text-sm font-mono text-gray-400 mb-2">Upload Payload Script</label>
             <div className="relative">
                <input
                  type="file"
                  id="script-upload"
                  accept=".lua,.txt"
                  onChange={handleFileUpload}
                  className="hidden"
                />
                <label
                  htmlFor="script-upload"
                  className="flex items-center justify-between w-full bg-black/50 border border-hacker-border/50 border-dashed p-3 rounded cursor-pointer hover:border-hacker-green hover:bg-hacker-green/5 transition-all group backdrop-blur-sm"
                >
                  <div className="flex items-center gap-3 overflow-hidden">
                    <div className="bg-hacker-dark p-1.5 rounded group-hover:bg-black transition-colors">
                      {fileName ? <FileText size={16} className="text-hacker-green" /> : <Upload size={16} className="text-gray-400" />}
                    </div>
                    <span className={`text-sm font-mono truncate ${fileName ? 'text-white' : 'text-gray-500'}`}>
                      {fileName || "Click to upload .lua / .txt"}
                    </span>
                  </div>
                  {fileName && (
                    <span className="text-xs text-gray-500 ml-2 whitespace-nowrap">Change</span>
                  )}
                </label>
             </div>
          </div>
        </div>

        {/* Code Preview */}
        <div className="relative group border border-hacker-border/50 rounded-lg overflow-hidden">
          <div className="bg-slate-900/80 backdrop-blur-md border-b border-hacker-border/50 p-3 flex justify-between items-center">
             <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-red-500/50"></div>
                <div className="w-3 h-3 rounded-full bg-yellow-500/50"></div>
                <div className="w-3 h-3 rounded-full bg-green-500/50"></div>
                <span className="ml-2 text-xs text-gray-500 font-mono">loader_preview.lua</span>
             </div>
             
             <div className="flex gap-2">
                <button
                  onClick={handleDownloadScript}
                  className="flex items-center gap-2 px-3 py-1.5 bg-blue-600/20 text-blue-400 border border-blue-600/50 rounded text-xs font-bold hover:bg-blue-600/30 transition-colors"
                >
                  <Download size={14} /> DOWNLOAD
                </button>
                <button
                  onClick={handleCopyScript}
                  className="flex items-center gap-2 px-3 py-1.5 bg-slate-700/80 text-white rounded text-xs font-bold hover:bg-slate-600 transition-colors border border-slate-500/50"
                >
                  {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
                  {copied ? 'COPIED' : 'COPY SCRIPT'}
                </button>
             </div>
          </div>
          
          <pre className="bg-black/90 p-4 md:p-6 overflow-x-auto text-xs md:text-sm font-mono text-gray-300 leading-relaxed max-h-[400px] overflow-y-auto">
            <code>
              {generateFullScript().split('\n').map((line, i) => (
                <div key={i} className="table-row">
                  <span className="table-cell select-none text-gray-700 pr-4 text-right w-8">{i + 1}</span>
                  <span className="table-cell whitespace-pre-wrap">
                    {line.includes('Key Expried') ? (
                       <span className="text-red-400">{line}</span>
                    ) : line.includes('getgenv') || line.includes('game:HttpGet') ? (
                       <span className="text-yellow-400">{line}</span>
                    ) : line.includes('PAYLOAD') ? (
                       <span className="text-gray-500 italic">{line}</span>
                    ) : (
                       line
                    )}
                  </span>
                </div>
              ))}
            </code>
          </pre>
        </div>

        <div className="mt-6 p-4 bg-blue-900/10 border border-blue-900/30 rounded-lg">
          <h3 className="text-blue-400 font-bold mb-2">How it works</h3>
          <ul className="list-disc list-inside text-sm text-gray-400 space-y-1">
            <li>Select a key from your dashboard to automatically insert it.</li>
            <li>Upload your actual script logic (Payload). It will replace the default placeholder.</li>
            <li>Download the final Loader script and execute it in your executor.</li>
            <li>The loader verifies the key before running your payload.</li>
          </ul>
        </div>
      </div>
    </div>
  );
};